### ISSUE TITLE
QARK cannot be build in ubuntu

### ISSUE THREAD

**Issue by cuckoo-linux** [linkedin/qark#147]
cuckoo@cuckoo-OptiPlex-9020:~/qark-master/qark$ python qarkMain.py 

 .d88888b.           d8888   8888888b.    888    d8P  
d88P" "Y88b         d88888   888   Y88b   888   d8P   
888     888        d88P888   888    888   888  d8P    
888     888       d88P 888   888   d88P   888d88K     
888     888      d88P  888   8888888P"    8888888b    
888 Y8b 888     d88P   888   888 T88b     888  Y88b   
Y88b.Y8b88P    d8888888888   888  T88b    888   Y88b  
 "Y888888"    d88P     888   888   T88b   888    Y88b 
        Y8b                                            
INFO - Initializing...
INFO - Identified Android SDK installation from a previous run.
INFO - Initializing QARK

Traceback (most recent call last):
  File "qarkMain.py", line 1282, in <module>
    nonAutomatedParseArgs()
  File "qarkMain.py", line 463, in nonAutomatedParseArgs
    main()
  File "qarkMain.py", line 588, in main
    manager.collectPlugins()
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginManager.py", line 540, in collectPlugins
    self.locatePlugins()
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginManager.py", line 443, in locatePlugins
    self._candidates, npc = self.getPluginLocator().locatePlugins()
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginFileLocator.py", line 434, in locatePlugins
    plugin_info = self._getInfoForPluginFromAnalyzer(analyzer, dirpath, filename)
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginFileLocator.py", line 388, in _getInfoForPluginFromAnalyzer
    plugin_info_dict,config_parser = analyzer.getInfosDictFromPlugin(dirpath, filename)
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginFileLocator.py", line 270, in getInfosDictFromPlugin
    raise ValueError("Missing *name* of the plugin in extracted infos.")
ValueError: Missing *name* of the plugin in extracted infos.

**Comment by nwalsh1995** [comment]
From the error there is a plugin that seems to be misconfigured. You can disable plugins by renaming each plugin in the `plugins/` directory to `{plugin-name}.yaspy-plugin.disabled`.

Have you created your own plugin? It might be causing issues.

**Comment by cuckoo-linux** [comment]
how to disable plugins??

**Comment by nwalsh1995** [comment]
@cuckoo-linux You can disable plugins by renaming each plugin in the plugins/ directory to {plugin-name}.yaspy-plugin.disabled

**Comment by cuckoo-linux** [comment]
i have renamed all yapsy plugins in plugin directory. like this(Manifest_File_Checks.yapsy-plugin.disabled,access_control.yapsy-plugin.disabled) but error is still there.
cuckoo@cuckoo-OptiPlex-9020:~/qark-master/qark$ python qarkMain.py 

 .d88888b.           d8888   8888888b.    888    d8P  
d88P" "Y88b         d88888   888   Y88b   888   d8P   
888     888        d88P888   888    888   888  d8P    
888     888       d88P 888   888   d88P   888d88K     
888     888      d88P  888   8888888P"    8888888b    
888 Y8b 888     d88P   888   888 T88b     888  Y88b   
Y88b.Y8b88P    d8888888888   888  T88b    888   Y88b  
 "Y888888"    d88P     888   888   T88b   888    Y88b 
        Y8b                                            
INFO - Initializing...
INFO - Identified Android SDK installation from a previous run.
INFO - Initializing QARK

Traceback (most recent call last):
  File "qarkMain.py", line 1282, in <module>
    nonAutomatedParseArgs()
  File "qarkMain.py", line 463, in nonAutomatedParseArgs
    main()
  File "qarkMain.py", line 588, in main
    manager.collectPlugins()
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginManager.py", line 540, in collectPlugins
    self.locatePlugins()
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginManager.py", line 443, in locatePlugins
    self._candidates, npc = self.getPluginLocator().locatePlugins()
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginFileLocator.py", line 434, in locatePlugins
    plugin_info = self._getInfoForPluginFromAnalyzer(analyzer, dirpath, filename)
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginFileLocator.py", line 388, in _getInfoForPluginFromAnalyzer
    plugin_info_dict,config_parser = analyzer.getInfosDictFromPlugin(dirpath, filename)
  File "/home/cuckoo/qark-master/qark/lib/yapsy/PluginFileLocator.py", line 270, in getInfosDictFromPlugin
    raise ValueError("Missing *name* of the plugin in extracted infos.")
ValueError: Missing *name* of the plugin in extracted infos.
cuckoo@cuckoo-OptiPlex-9020:~/qark-master/qark$ python qarkMain.py 
Traceback (most recent call last):
  File "qarkMain.py", line 58, in <module>
    from lib.yapsy.PluginManager import PluginManager
ImportError: No module named yapsy.PluginManager

**Comment by nwalsh1995** [comment]
That's weird. I would suggest you to re-clone this repo and try again.

**Comment by nwalsh-lnk** [comment]
@cuckoo-linux, did you end up getting this to work?
