### ISSUE TITLE
stuck when Decompilating .

### ISSUE THREAD

**Issue by easternHong** [linkedin/qark#16]
```
JD CORE 100%|#################################################################|
Procyon  94%|#############################################################    |
CFR 100%|#####################################################################|
```

 it takes too long ,but nothing updates.

when i press  Ctrl+c ,it shows:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/xxx/python/qark-master/modules/unpackAPK.py", line 253, in procyon
Traceback (most recent call last):
  File "qark.py", line 613, in <module>
    line = process.stdout.readline()
```

**Comment by SecBro1** [comment]
If you run into an APK that stalls while decompiling, you can simply press
the C key, as directed in the on-screen instructions. This will stop the
decompiling and proceed with whatever was already decompiled to that point.

It is recommended to at least allow one of the decompilers to finish, so
you at least get one decompilers best effort.

**Comment by easternHong** [comment]
thanks a lot.
