### ISSUE TITLE
Attempt to analyze the apk file crashes

### ISSUE THREAD

**Issue by agap** [linkedin/qark#215]
Hey, I'm on the most recent version of qark v2 (commit `a6905f6b5429f58b583eaea618c5c3f0a142bbbf`) and when I'm trying to perform

`sudo qark  --apk /path/to/application.apk --debug`

everything goes fine until it's failing with the following stacktrace:

```
Running scans...
Finish scans...
Writing report...
Traceback (most recent call last):
  File "/usr/local/bin/qark", line 11, in <module>
    load_entry_point('qark==2.0', 'console_scripts', 'qark')()
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/qark/qark.py", line 68, in cli
    click.secho("Finish writing report to %s...", report_path)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/utils.py", line 259, in echo
    file.write(message)
AttributeError: 'str' object has no attribute 'write'
```

I was not digging much into that issue, but it looks like qark (or some of its libraries) tries to use the string object as an instance of file class. Is this something which might be caused by the wrong version of one of the libraries used by qark?

Thank you!

**Comment by agap** [comment]
Here's the list of the python packages installed on my system, in case it might be related to the project:
```
asn1crypto==0.24.0
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
cheroot==6.0.0
CherryPy==14.0.1
click==6.7
cryptography==2.2.1
enum34==1.1.6
Flask==0.12.2
idna==2.6
ipaddress==1.0.19
itsdangerous==0.24
javalang==0.11.0
Jinja2==2.10
MarkupSafe==1.0
mercurial==4.1.2
more-itertools==4.1.0
Pillow==5.0.0
pluginbase==0.5
ply==3.11
portend==2.2
pycparser==2.18
pyOpenSSL==17.5.0
pytz==2018.3
qark==2.0
requests==2.18.4
simplejson==3.13.2
six==1.11.0
SQLAlchemy==1.2.5
tempora==1.11
urllib3==1.22
web.py==0.40.dev1
Werkzeug==0.14.1
```

**Comment by nwalsh1995** [comment]
Hi @agap, thanks for continuing reporting issues with QARK's v2. We don't have a very big userbase on it so this is much appreciated for us to work out bugs. Have you updated since #211 was merged? That PR addressed what appears to be this issue.

**Comment by agap** [comment]
Yep, looks like this was it. Thank you for the help!
