### ISSUE TITLE
Problem running on master

### ISSUE THREAD

**Issue by einhverfr** [linkedin/qark#25]
[chris@chris-g50 qark]$ python qark.py 
    Traceback (most recent call last):
      File "qark.py", line 24, in <module>
        from modules import common,findExtras,webviews, report, unpackAPK
      File "/home/chris/github/qark/modules/common.py", line 26, in <module>
        from lib.blessed import *
      File "/home/chris/github/qark/lib/blessed/__init__.py", line 12, in <module>
        from terminal import Terminal 
    ImportError: cannot import name Terminal
    [chris@chris-g50 qark]$ 

This occurs on master (not related to my current work). Maybe a circular dependency?

**Comment by einhverfr** [comment]
braindead issue on my side.  Please ignore.
