### ISSUE TITLE
Fatal error in writing report

### ISSUE THREAD

**Issue by alonf1983** [linkedin/qark#268]
Hi.
after the scans i get the following error:

Running scans...
Finish scans...
Writing report...
Traceback (most recent call last):
  File "/usr/local/bin/qark", line 9, in <module>
    load_entry_point('qark==2.0', 'console_scripts', 'qark')()
  File "/Users/alonf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alonf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/alonf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alonf/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/alonf/Library/Python/2.7/lib/python/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/qark-2.0-py2.7.egg/qark/qark.py", line 67, in cli
    report_path = report.generate(file_type=report_type)
  File "/Library/Python/2.7/site-packages/qark-2.0-py2.7.egg/qark/report.py", line 63, in generate
    template = jinja_env.get_template('{file_type}_report.jinja'.format(file_type=file_type))
  File "/Library/Python/2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Library/Python/2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Library/Python/2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Python/2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: html_report.jinja

COuld you help please?

**Comment by nwalsh-lnk** [comment]
This should be fixed in the newest version. Please update.
`pip install --upgrade qark`
