### ISSUE TITLE
Getting Error ModuleNotFoundError: No module named 'qark.apk_builder'; 'qark' is not a package.

### ISSUE THREAD

**Issue by testSatya007** [linkedin/qark#288]
I am getting error when running the command "python qark.py". Below are the error..

Traceback (most recent call last):
  File "qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
  File "F:\PenTesting Tools\QARK\qark\qark\qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
ModuleNotFoundError: No module named 'qark.apk_builder'; 'qark' is not a package

**Comment by localacct** [comment]
Hi

I know that this issue has been closed but I am encountering the same issue here. I read the README file and it said to use these steps
````
  ~ git clone https://github.com/linkedin/qark
  ~ cd qark
  ~ pip install -r requirements.txt
  ~ pip install . --user  # --user is only needed if not using a virtualenv
  ~ qark --help
````
I managed to complete the first four steps but when running ````qark --help````, it just says "command not found" and I also tried the same command while inside the qark sub folder where qark.py is located.

There were no issues with the installation, all the requirements were satisfied etc.
