### ISSUE TITLE
exec command failed -- bug report

### ISSUE THREAD

**Issue by yougar0** [linkedin/qark#293]
below is error info:

A:\android>qark --apk mojitianqi_7070802.apk
Decompiling...
Error running dex2jar command: b'C:\\\\Users\\\\yougar\\\\AppData\\\\Roaming\\\\
Python\\\\Python36\\\\site-packages\\\\qark\\\\decompiler\\\\..\\\\lib\\\\dex2ja
r-2.0\\\\d2j-dex2jar.bat A:\\\\android\\\\build\\\\qark\\\\classes.dex -o A:\\\\
android\\\\build\\\\qark\\\\mojitianqi_7070802.jar'
Traceback (most recent call last):
  File "C:\Users\yougar\AppData\Roaming\Python\Python36\site-packages\qark\decom
piler\decompiler.py", line 217, in _run_dex2jar
    ret_code = subprocess.call(shlex.split(dex2jar_command))
  File "c:\program files\python36\lib\shlex.py", line 305, in split
    return list(lex)
  File "c:\program files\python36\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\program files\python36\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\program files\python36\lib\shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'bytes' object has no attribute 'read'
Error running dex2jar command

I change 
 File "C:\Users\yougar\AppData\Roaming\Python\Python36\site-packages\qark\decom
piler\decompiler.py", line 217, in _run_dex2jar
    ret_code = subprocess.call(shlex.split(dex2jar_command))
to 
ret_code = subprocess.call(shlex.split(dex2jar_command.decode(encoding="utf-8")))

then fixes it.

**Comment by krviolent** [comment]
I faced this is issue in Windows, though in Ubuntu there was no such error

**Comment by ibrahimbroachwala** [comment]
Is this Issue solved? I am facing the same issue

**Comment by XhstormR** [comment]
same issue

**Comment by GwenTheKween** [comment]
still having this same issue on windows.

**Comment by sagarkm** [comment]
i have the same issue on Windows 10 with Python 3.9

**Comment by fawadbutt** [comment]
i facing the same issue can't be able to decompile.  i using python 3.10 o n window 10,
