### ISSUE TITLE
Qark on Windows - Not working

### ISSUE THREAD

**Issue by gaurav1987127** [linkedin/qark#306]
Hi, I am installing qark on windows and facing challenge. I have followed the below commands but still it's not working. Please help me.

~ pip install -r requirements.txt
~ pip install . --user

C:\Software\Android\Static_Analysis\qark-master\qark>pip install qark

Requirement already satisfied: qark in c:\users\gaurav_w\appdata\roaming\python\python27\site-packages (3.0.1)

Requirement already satisfied: pluginbase in c:\python27\lib\site-packages (from qark) (0.5)

Requirement already satisfied: click in c:\python27\lib\site-packages (from qark) (6.7)

Requirement already satisfied: jinja2 in c:\python27\lib\site-packages (from qark) (2.10)

Requirement already satisfied: enum34; python_version < "3.4" in c:\python27\lib\site-packages (from qark) (1.1.6)

Requirement already satisfied: requests[security] in c:\python27\lib\site-packages (from qark) (2.18.4)

Requirement already satisfied: javalang in c:\python27\lib\site-packages (from qark) (0.11.0)

Requirement already satisfied: six in c:\python27\lib\site-packages (from qark) (1.11.0)

Requirement already satisfied: MarkupSafe>=0.23 in c:\python27\lib\site-packages (from jinja2->qark) (1.0)

Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests[security]->qark) (2.6)

Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests[security]->qark) (1.22)

Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests[security]->qark) (2018.1.18)

Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests[security]->qark) (3.0.4)

Requirement already satisfied: cryptography>=1.3.4; extra == "security" in c:\python27\lib\site-packages (from requests[security]->qark) (2.2.1)

Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in c:\python27\lib\site-packages (from requests[security]->qark) (17.5.0)

Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in c:\python27\lib\site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->qark) (1.11.5)

Requirement already satisfied: asn1crypto>=0.21.0 in c:\python27\lib\site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->qark) (0.24.0)

Requirement already satisfied: ipaddress; python_version < "3" in c:\python27\lib\site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->qark) (1.0.19)

Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; extra == "security"->requests[security]->qark) (2.18)

**C:\Software\Android\Static_Analysis\qark-master\qark>qark --help
'qark' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by nwalsh1995** [comment]
You must add the location of where pip puts the binaries to your PATH so that they can be executed.

**Comment by gaurav1987127** [comment]
Hi, I have tried with qark.py but still it not working. please find the response

C:\Software\Android\Static_Analysis\qark-master\qark>qark.py
Traceback (most recent call last):
  File "C:\Software\Android\Static_Analysis\qark-master\qark\qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
  File "C:\Software\Android\Static_Analysis\qark-master\qark\qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
ImportError: No module named apk_builder

**Comment by nwalsh1995** [comment]
@gaurav1987127 qark is meant to be ran just as `qark` not as `python qark`. 

Find out the directory that `qark` was installed to when you ran `pip install qark` and navigate there and try to run it.

**Comment by gaurav1987127** [comment]
I have tried the alternative mentioned by you but it's still not working. Kindly get this issue fixed. Let me know if this is planned to be fixed in qark new version in future.

**Comment by nwalsh1995** [comment]
@gaurav1987127 Please include the terminal output of what is going wrong and we can fix any issues

**Comment by gaurav1987127** [comment]
Hi, As mentioned above and as per your inputs, i have followed following steps

1. Installed qark using "pip install qark" - Please find the output

C:\Software\Android\Static_Analysis\qark-master\qark>pip install qark
Requirement already satisfied: qark in c:\users\gaurav_w\appdata\roaming\python\python27\site-packages (3.0.1)
Requirement already satisfied: pluginbase in c:\python27\lib\site-packages (from qark) (0.5)
Requirement already satisfied: click in c:\python27\lib\site-packages (from qark) (6.7)
Requirement already satisfied: jinja2 in c:\python27\lib\site-packages (from qark) (2.10)
Requirement already satisfied: enum34; python_version < "3.4" in c:\python27\lib\site-packages (from qark) (1.1.6)
Requirement already satisfied: requests[security] in c:\python27\lib\site-packages (from qark) (2.18.4)
Requirement already satisfied: javalang in c:\python27\lib\site-packages (from qark) (0.11.0)
Requirement already satisfied: six in c:\python27\lib\site-packages (from qark) (1.11.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\python27\lib\site-packages (from jinja2->qark) (1.0)
Requirement already satisfied: idna<2.7,>=2.5 in c:\python27\lib\site-packages (from requests[security]->qark) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\python27\lib\site-packages (from requests[security]->qark) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\python27\lib\site-packages (from requests[security]->qark) (2018.1.18)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python27\lib\site-packages (from requests[security]->qark) (3.0.4)
Requirement already satisfied: cryptography>=1.3.4; extra == "security" in c:\python27\lib\site-packages (from requests[security]->qark) (2.2.1)
Requirement already satisfied: pyOpenSSL>=0.14; extra == "security" in c:\python27\lib\site-packages (from requests[security]->qark) (17.5.0)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in c:\python27\lib\site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->qark) (1.11.5)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\python27\lib\site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->qark) (0.24.0)
Requirement already satisfied: ipaddress; python_version < "3" in c:\python27\lib\site-packages (from cryptography>=1.3.4; extra == "security"->requests[security]->qark) (1.0.19)
Requirement already satisfied: pycparser in c:\python27\lib\site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; extra == "security"->requests[security]->qark) (2.18)

2. I have sent path environmental variables to the following as per above output. Refer attached image also
C:\Software\Android\Static_Analysis\qark-master\qark
C:\Users\gaurav_w\AppData\Roaming\Python\Python27\site-packages\qark
C:\Users\gaurav_w\AppData\Roaming\Python\Python27\site-packages

![image](https://user-images.githubusercontent.com/46870614/51707321-e6978500-2046-11e9-8f29-c0dcd60c3938.png)

3. After this, I tried to run qark through multiple locations and i received following output

C:\Software\Android\Static_Analysis\qark-master\qark>qark
'qark' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\gaurav_w\AppData\Roaming\Python\Python27\site-packages\qark>
C:\Users\gaurav_w\AppData\Roaming\Python\Python27\site-packages\qark>qark
'qark' is not recognized as an internal or external command,
operable program or batch file.


Kindly help me with the resolution in details. Let me know in case any further details required from my side

**Comment by nwalsh1995** [comment]
@gaurav1987127 you need to add the `bin/` folder to your path. 

I think it should be in `c:\python27\bin`

**Comment by Tarvinder91** [comment]
# pip show qark
This should show the path where qark is installed. Verify if the qark.exe is present in that folder. Else there would be a folder 'Scripts' just one level up , where qark.exe could be found.

For me it ws installed in C:\Users\Administrator\AppData\Roaming\Python\Python36\Scripts. Add this in PATH environment variable.

**Comment by AlinaJavaid** [comment]
hi @gaurav1987127 ? had you solved your issue on windows?

**Comment by ghost** [comment]
> # pip show qark
> This should show the path where qark is installed. Verify if the qark.exe is present in that folder. Else there would be a folder 'Scripts' just one level up , where qark.exe could be found.
> 
> For me it ws installed in C:\Users\Administrator\AppData\Roaming\Python\Python36\Scripts. Add this in PATH environment variable.


Thanks a lot. You saved my day
Must marked as solution

**Comment by shreymistry** [comment]
I am facing the same problem. I am attaching few screenshots if you can find the problem
![Screenshot (275)](https://user-images.githubusercontent.com/69461078/115542344-d02c1280-a2bd-11eb-8d06-d20ae1ccd057.png)
![Screenshot (276)](https://user-images.githubusercontent.com/69461078/115542590-0b2e4600-a2be-11eb-8cdc-067aac125899.png)
![Screenshot (351)](https://user-images.githubusercontent.com/69461078/115542899-62ccb180-a2be-11eb-9e74-8f175581e447.png)
