### ISSUE TITLE
Qark crashes when java version does not match regex

### ISSUE THREAD

**Issue by a-ion314** [linkedin/qark#307]
Running Qark on a machine with Java version 18.9 will cause it to crash with the following message:

Detail Error Information in File ./classes-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
Traceback (most recent call last):
  File "/Users/oskars/Library/Python/2.7/bin/qark", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/oskars/Library/Python/2.7/lib/python/site-packages/qark/qark.py", line 83, in cli
    decompiler = Decompiler(path_to_source=source, build_directory=build_path)
  File "/Users/oskars/Library/Python/2.7/lib/python/site-packages/qark/decompiler/decompiler.py", line 80, in __init__
    self.manifest_path = self.run_apktool()
  File "/Users/oskars/Library/Python/2.7/lib/python/site-packages/qark/decompiler/decompiler.py", line 134, in run_apktool
    java_version = get_java_version()
  File "/Users/oskars/Library/Python/2.7/lib/python/site-packages/qark/decompiler/decompiler.py", line 253, in get_java_version
    return version_regex.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I believe this is due to Java version 18.9 not following the x.y.z format for its versioning thats its failing to get the version number. As a result version_regex becomes 'None'. JAVA_VERSION_REGEX in decompiler.py should be changed to include these shorter version numbers.

**Comment by mr-gosh** [comment]
for me - the fix doesn't work - i still get the same error - possible this doesn't work with openjdk?
it seems to be working with openjdk-8

**Comment by a-ion314** [comment]
@mr-gosh 
What version of java has this issue?
Could you tell me what shows up when you run "java -version" when using that specific version?

**Comment by fabelx** [comment]
For me - the fix doesn't work - I still get the same error.
```
(venv) name@name-MS-7C51:~/Documents/qark$ java -version
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

```
