### ISSUE TITLE
Windows Python2 - ImportError: No module named termios 

### ISSUE THREAD

**Issue by vizzdoom** [linkedin/qark#308]
Qark interactive mode doesn't work on Windows.

Windows 10, Python 2.7.14 and Python 3.6.8.

`d:\Android\qark\qark>c:\Python2\python.exe qarkMain.py
Traceback (most recent call last):
  File "qarkMain.py", line 28, in <module>
    from modules import common
  File "d:\Android\qark\qark\modules\common.py", line 28, in <module>
    from lib.blessed import *
  File "d:\Android\qark\qark\lib\blessed\__init__.py", line 12, in <module>
    from terminal import Terminal
  File "d:\Android\qark\qark\lib\blessed\terminal.py", line 7, in <module>
    import termios
ImportError: No module named termios`

**Comment by Thirumurugan19** [comment]
Hi all , Me too getting same error on Windows with 2.7 python and let us know which is New version of qark ?
