### ISSUE TITLE
QARk failed to extract zipped apk

### ISSUE THREAD

**Issue by sudoshekhu** [linkedin/qark#312]
root@kali:~/Desktop/qark# qark --apk DiGieye.apk 
Decompiling...
Failed to extract zipped APK from /root/Desktop/qark/DiGieye.apk to /root/Desktop/qark/build/qark
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/qark/decompiler/decompiler.py", line 227, in unzip_file
    zipped_apk = zipfile.ZipFile(file_to_unzip, "r")
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
Failed to extract zipped APK
root@kali:~/Desktop/qark# qar

**Comment by nwalsh-lnk** [comment]
Can you update to the newest version and try again? If it doesn't work I suspect your APK file is not actually formed correctly
