### ISSUE TITLE
KeyError: 'type' when scanning source folder

### ISSUE THREAD

**Issue by bnt2025** [linkedin/qark#313]
When a scan against source folder I get the error below. I get the same error when running qark on Windows 10 against the same source code. 

After some fault finding it seems to be triggered by the following line;
``` java 
import android.content.Intent;
```
If I comment out this line from each of the files then qark completes successfully. Uncommenting reintroduces this error;

``` bash
usernam@ubuntu:~$ qark --java ./
Decompiling...
Running scans...
Traceback (most recent call last):
  File "/home/usernam/.local/bin/qark", line 10, in <module>
    sys.exit(cli())
  File "/home/usernam/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/usernam/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/usernam/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/usernam/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/usernam/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/usernam/.local/lib/python2.7/site-packages/qark/qark.py", line 91, in cli
    scanner.run()
  File "/home/usernam/.local/lib/python2.7/site-packages/qark/scanner/scanner.py", line 64, in run
    self._run_checks(plugins)
  File "/home/usernam/.local/lib/python2.7/site-packages/qark/scanner/scanner.py", line 74, in _run_checks
    current_file_subject.notify(filepath)  # All the plugins will be running now
  File "/home/usernam/.local/lib/python2.7/site-packages/qark/scanner/scanner.py", line 143, in notify
    observer.update(file_path, call_run=True)
  File "/home/usernam/.local/lib/python2.7/site-packages/qark/scanner/plugin.py", line 192, in update
    self.run()
  File "/home/usernam/.local/lib/python2.7/site-packages/qark/scanner/../plugins/generic/task_affinity.py", line 29, in run
    description = TASK_AFFINITY_DESCRIPTION.format("NEW")
KeyError: 'type'
```

**Comment by nwalsh1995** [comment]
Please update to the newest version of qark. this is fixed in qark==4.0.0
