### ISSUE TITLE
Error running dex2jar

### ISSUE THREAD

**Issue by simplevulnerabilitymanager** [linkedin/qark#324]
test.apk is:
https://github.com/dineshshetty/Android-InsecureBankv2/releases/download/2.3.1/InsecureBankv2.apk

Run in Kali Linux last version.

Debug logging enabled
Decompiling...
Unpacking apk
Running dex2jar with command /usr/local/lib/python2.7/dist-packages/qark-4.0.0-py2.7.egg/qark/decompiler/../lib/dex2jar-2.0/d2j-dex2jar.sh /root/qark/build/qark/classes.dex -o /root/qark/build/qark/test.apk_30_03_2019-00_40_38.jar
dex2jar /root/qark/build/qark/classes.dex -> /root/qark/build/qark/test.apk_30_03_2019-00_40_38.jar
Exception in thread "main" java.lang.OutOfMemoryError
        at java.base/java.util.zip.Deflater.init(Native Method)
        at java.base/java.util.zip.Deflater.<init>(Deflater.java:208)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getDeflater(ZipFileSystem.java:1670)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem$EntryOutputStreamDef.<init>(ZipFileSystem.java:1423)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.writeEntry(ZipFileSystem.java:1190)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.sync(ZipFileSystem.java:1238)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.lambda$close$2(ZipFileSystem.java:278)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.close(ZipFileSystem.java:277)
        at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:273)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:108)
        at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:288)
        at com.googlecode.dex2jar.tools.Dex2jarCmd.main(Dex2jarCmd.java:32)
Error running dex2jar command: /usr/local/lib/python2.7/dist-packages/qark-4.0.0-py2.7.egg/qark/decompiler/../lib/dex2jar-2.0/d2j-dex2jar.sh /root/qark/build/qark/classes.dex -o /root/qark/build/qark/test.apk_30_03_2019-00_40_38.jar
Error running dex2jar
----------------------------------------------------------------------------------------------------

**Comment by nwalsh1995** [comment]
From your error, it is clear: `Exception in thread "main" java.lang.OutOfMemoryError`. I'm guessing your machine has really low amount of memory in use and when trying to run some applications it goes out of memory. Since we don't control dex2jar, nothing we can do.
