### ISSUE TITLE
Issues parsing AndroidManifest files

### ISSUE THREAD

**Issue by 7a** [linkedin/qark#33]
When you try to analyse the android webview base.apk from a device running Android 6, you get:

Traceback (most recent call last):
  File "qark.py", line 494, in <module>
    manifestInXML = minidom.parseString(mfbuff).toxml()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 22, column 14

The Manifest file extracted via apktool is:

-----
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.google.android.webview" platformBuildVersionCode="23" platformBuildVersionName="6.0-2166767">
    <uses-feature android:name="android.hardware.touchscreen" android:required="false"/>
    <application android:icon="@drawable/icon_webview" android:label="Android System WebView" android:multiArch="true">
        <activity android:label="@string/license_activity_title" android:name="com.android.webview.chromium.LicenseActivity">
            <intent-filter>
                <action android:name="android.settings.WEBVIEW_LICENSE"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>
            <meta-data android:name="com.android.settings.PRIMARY_PROFILE_CONTROLLED" android:value="true"/>
        </activity>
        <provider android:authorities="com.google.android.webview.LicenseContentProvider" android:exported="true" android:name="com.android.webview.chromium.LicenseContentProvider"/>
        <meta-data android:name="com.android.webview.WebViewLibrary" android:value="libwebviewchromium.so"/>
    </application>
</manifest>
```

**Comment by tushardalvi** [comment]
We have instrumented apktool to resolve the parsing issues. Please let us know if you are still able to reproduce this issue using any other APK.

**Comment by schniggie** [comment]
Just installed the latest version and get the same error when trying to open the latest Netflix app (https://www.apkmirror.com/apk/netflix-inc/netflix/netflix-6-5-2-build-28341-release/netflix-6-5-2-build-28341-android-apk-download/).

```
Here is my output:
Enter your choice:1

Please enter the full path to your APK (ex. /foo/bar/pineapple.apk):
Path:/root/Downloads/com.netflix.mediaclient_6.5.2_build_28341.apk
INFO - Unpacking /root/Downloads/com.netflix.mediaclient_6.5.2_build_28341.apk
INFO - Zipfile: <zipfile.ZipFile object at 0x7f4665696990>
INFO - Extracted APK to /root/Downloads/com.netflix.mediaclient_6.5.2_build_28341/
/root/Downloads/apktool/AndroidManifest.xml
Traceback (most recent call last):
  File "qark/qarkMain.py", line 1284, in <module>
    nonAutomatedParseArgs()
  File "qark/qarkMain.py", line 465, in nonAutomatedParseArgs
    main()
  File "qark/qarkMain.py", line 664, in main
    common.manifest = minidom.parseString(common.manifest).toxml()
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 27, column 292
```

Thanks and BR schniggie
