### ISSUE TITLE
Qark not running properly after building it

### ISSUE THREAD

**Issue by Blueeyes3** [linkedin/qark#330]
Dear Team,

I am facing the below error stack when trying to run qark in windows system.

**System used:**
Operating system: Windows 
Python version: 2.7.15
Qark version: 4.0.0

**Steps followed for installation:**
cd qark
pip install -r requirements.txt
pip install . 

When running the below command, the pasted error trace is observed.

command: qark --apk com.retard.apk

**Error Stack:**
Decompiling...
-e/-o can only used with one file
Input file (\qark-master\qark-master\build\qark\apktool) was not found or
 was not readable.
Traceback (most recent call last):
  File "C:\Python27\Scripts\qark-script.py", line 11, in <module>
    load_entry_point('qark==4.0.0', 'console_scripts', 'qark')()
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func

    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\qark\qark.py", line 87, in cli
    decompiler = Decompiler(path_to_source=source, build_directory=build_path)
  File "c:\python27\lib\site-packages\qark\decompiler\decompiler.py", line 80, i
n __init__
    self.manifest_path = self.run_apktool()
  File "c:\python27\lib\site-packages\qark\decompiler\decompiler.py", line 163,
in run_apktool
    os.path.join(self.build_directory, "AndroidManifest.xml"))
  File "c:\python27\lib\shutil.py", line 316, in move
    copy2(src, real_dst)
  File "c:\python27\lib\shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "c:\python27\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'C:\\qark-master\\
qark-master\\build\\qark\\apktool\\AndroidManifest.xml'

**Comment by Blueeyes3** [comment]
Issue seems to be apply only for python version 2.7.15. Seems to be resolved in python 3.x

**Comment by ST0new** [comment]
在 python3 中遇到同样的问题
