### ISSUE TITLE
Crash during decompile - Heavily obfuscated exception ranges found!

### ISSUE THREAD

**Issue by alonf1983** [linkedin/qark#342]
hi
during decompile we have received the following error and the scan is freezes.

INFO:  Decompiling class o/class_4488
WARN:           Method $$c (BSI)Ljava/lang/String; couldn't be decompiled.
java.lang.RuntimeException: parsing failure!
	at org.jetbrains.java.decompiler.modules.decompiler.DomHelper.parseGraph(DomHelper.java:203)
	at org.jetbrains.java.decompiler.main.rels.MethodProcessorRunnable.codeToJava(MethodProcessorRunnable.java:116)
	at org.jetbrains.java.decompiler.main.rels.ClassWrapper.init(ClassWrapper.java:62)
	at org.jetbrains.java.decompiler.main.ClassesProcessor.initWrappers(ClassesProcessor.java:369)
	at org.jetbrains.java.decompiler.main.ClassesProcessor.writeClass(ClassesProcessor.java:316)
	at org.jetbrains.java.decompiler.main.Fernflower.getClassContent(Fernflower.java:114)
	at org.jetbrains.java.decompiler.struct.ContextUnit.save(ContextUnit.java:133)
	at org.jetbrains.java.decompiler.struct.StructContext.saveContext(StructContext.java:58)
	at org.jetbrains.java.decompiler.main.Fernflower.decompileContext(Fernflower.java:87)
	at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.decompileContext(ConsoleDecompiler.java:120)
	at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.main(ConsoleDecompiler.java:82)
WARN:           Heavily obfuscated exception ranges found!

could you help please?

**Comment by joseph-acc** [comment]
Seeing the same error
