### ISSUE TITLE
Failed to find AndroidManifest.xml

### ISSUE THREAD

**Issue by Brumstar** [linkedin/qark#344]
Hi all,

I have installed qark and have been attempting to use the tool with the following command:

~~~
qark --apk stuff.apk
~~~

However, this results in the following error:

~~~
Decompiling...
-e/-o can only used with one file
Input file (Shared/build/qark/apktool) was not found or was not readable.
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 550, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hgfs/Pentest Shared/build/qark/apktool/AndroidManifest.xml' -> '/mnt/hgfs/Pentest Shared/build/qark/AndroidManifest.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redacted/.local/bin/qark", line 11, in <module>
    sys.exit(cli())
  File "/home/redacted/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/redacted/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/redacted/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/redacted/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/redacted/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/redacted/.local/lib/python3.6/site-packages/qark/qark.py", line 83, in cli
    decompiler = Decompiler(path_to_source=source, build_directory=build_path)
  File "/home/redacted/.local/lib/python3.6/site-packages/qark/decompiler/decompiler.py", line 80, in __init__
    self.manifest_path = self.run_apktool()
  File "/home/redacted/.local/lib/python3.6/site-packages/qark/decompiler/decompiler.py", line 163, in run_apktool
    os.path.join(self.build_directory, "AndroidManifest.xml"))
  File "/usr/lib/python3.6/shutil.py", line 564, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/hgfs/Pentest Shared/build/qark/apktool/AndroidManifest.xml'
~~~

Can anyone tell me what is going wrong?

Thanks,

**Comment by xeroxnir** [comment]
Check moving to a directory and/or apk name without spaces. That worked for me.

**Comment by Brumstar** [comment]
Thanks @xeroxnir, this was this issue. Closing.
