### ISSUE TITLE
Error while scanning (parsing). Unterminated character/string literal at " ' "

### ISSUE THREAD

**Issue by krviolent** [linkedin/qark#345]
Running scans...
Traceback (most recent call last):
  File "/usr/local/bin/qark", line 11, in <module>
    load_entry_point('qark==4.0.0', 'console_scripts', 'qark')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/qark.py", line 94, in cli
    scanner.run()
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/scanner/scanner.py", line 64, in run
    self._run_checks(plugins)
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/scanner/scanner.py", line 78, in _run_checks
    current_file_subject.notify(filepath)
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/scanner/scanner.py", line 125, in notify
    observer.update(file_path, call_run=True)
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/scanner/plugin.py", line 239, in update
    super(CoroutinePlugin, self).update(file_path)
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/scanner/plugin.py", line 185, in update
    JavaASTPlugin.java_ast = javalang.parse.parse(self.file_contents)
  File "/usr/local/lib/python3.6/dist-packages/javalang-0.12.0-py3.6.egg/javalang/parse.py", line 52, in parse
    parser = Parser(tokens)
  File "/usr/local/lib/python3.6/dist-packages/javalang-0.12.0-py3.6.egg/javalang/parser.py", line 95, in __init__
    self.tokens = util.LookAheadListIterator(tokens)
  File "/usr/local/lib/python3.6/dist-packages/javalang-0.12.0-py3.6.egg/javalang/util.py", line 92, in __init__
    self.list = list(iterable)
  File "/usr/local/lib/python3.6/dist-packages/javalang-0.12.0-py3.6.egg/javalang/tokenizer.py", line 531, in tokenize
    self.read_string()
  File "/usr/local/lib/python3.6/dist-packages/javalang-0.12.0-py3.6.egg/javalang/tokenizer.py", line 201, in read_string
    self.error('Unterminated character/string literal')
  File "/usr/local/lib/python3.6/dist-packages/javalang-0.12.0-py3.6.egg/javalang/tokenizer.py", line 572, in error
    raise error
javalang.tokenizer.LexerError: Unterminated character/string literal at "'", line 724: java.lang.UnsupportedOperationException: Can't linearise an unstructured statement

**Comment by rubaramanan** [comment]
Same issues how can be sortout?

**Comment by krviolent** [comment]
I don't remember clearly how I solved this issue, may be I modified module **tokenizer.py**
