### ISSUE TITLE
Unable to run plugin

### ISSUE THREAD

**Issue by krviolent** [linkedin/qark#346]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/scanner/plugin.py", line 194, in update
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/scanner/../plugins/webview/set_allow_content_access.py", line 29, in run
    severity=self.severity))
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/plugins/webview/helpers.py", line 72, in webview_default_vulnerable
    if valid_set_method_bool(method_invocation=selector, str_bool="false", method_name=method_name):
  File "/usr/local/lib/python3.6/dist-packages/qark-4.0.0-py3.6.egg/qark/plugins/webview/helpers.py", line 25, in valid_set_method_bool
    if not method_invocation.arguments or not isinstance(method_invocation.arguments[0], Literal):
AttributeError: 'MemberReference' object has no attribute 'arguments'

**Comment by god599** [comment]
does this issue had been fixed？

**Comment by krviolent** [comment]
> 

i'm not actually remember, but think I had changed code somehow and it finally worked
