### ISSUE TITLE
unable to run 

### ISSUE THREAD

**Issue by hackersden09** [linkedin/qark#359]
[root@anonymous:~/Desktop/weapons/apppen/qark/qark]#  python qark.py
Traceback (most recent call last):
  File "qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
  File "/root/Desktop/weapons/apppen/qark/qark/qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
ImportError: No module named apk_builder

**Comment by jmkebalo** [comment]
Hello,
As described on the README, [installation part](https://github.com/linkedin/qark#installation), you first need to install the app, using `pip install .` or `pip install . --user`

It will build an .exe, and you will simply call `qark --help`  from your command prompt to invoke the tool.
Regards,
