### ISSUE TITLE
Getting below error - D:\qark\qark-master\qark-master\qark>python qark.py Traceback (most recent call last):   File "qark.py", line 11, in <module>     from qark.apk_builder import APKBuilder   File "D:\qark\qark-master\qark-master\qark\qark.py", line 11, in <module>     from qark.apk_builder import APKBuilder ImportError: No module named apk_builder

### ISSUE THREAD

**Issue by ajaysingh-qa** [linkedin/qark#362]

**Comment by Franciscooak** [comment]
I'm having trouble running qark. appears the message below? can you help me
kali@kali:~/qark/qark$ python3 qark.py
Traceback (most recent call last):
  File "qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
  File "/home/kali/qark/qark/qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
ModuleNotFoundError: No module named 'qark.apk_builder'; 'qark' is not a package
kali@kali:~/qark/qark$ python qark.py
Traceback (most recent call last):
  File "qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
  File "/home/kali/qark/qark/qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
ImportError: No module named apk_builder

**Comment by evidi** [comment]
You cant start qark using the command python qark.py. You can try to use qark --help for more options.
