### ISSUE TITLE
Failed to run APKTool

### ISSUE THREAD

**Issue by SameerShelarr** [linkedin/qark#376]
Hello, Facing a issue please have a  look.

C:\Users\samee>qark --apk C:\Users\samee\Desktop\Test\test.apk
Decompiling...
dex2jar C:\Users\samee\build\qark\classes.dex -> C:\Users\samee\build\qark\test.jar
Detail Error Information in File .\classes-error.zip
Please report this file to http://code.google.com/p/dex2jar/issues/entry if possible.
Failed to run APKTool with command: b'java -Djava.awt.headless=true -jar C:\\\\Users\\\\samee\\\\AppData\\\\Roaming\\\\Python\\\\Python39\\\\site-packages\\\\qark\\\\decompiler\\\\..\\\\lib\\\\apktool/apktool.jar d C:\\\\Users\\\\samee\\\\Desktop\\\\Test\\\\test.apk --no-src --force -m --output C:\\\\Users\\\\samee\\\\build\\\\qark\\\\apktool'
Traceback (most recent call last):
  File "C:\Users\samee\AppData\Roaming\Python\Python39\site-packages\qark\decompiler\decompiler.py", line 155, in run_apktool
    subprocess.call(shlex.split(custom_apktool_command))
  File "c:\users\samee\appdata\local\programs\python\python39-32\lib\shlex.py", line 315, in split
    return list(lex)
  File "c:\users\samee\appdata\local\programs\python\python39-32\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "c:\users\samee\appdata\local\programs\python\python39-32\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "c:\users\samee\appdata\local\programs\python\python39-32\lib\shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'bytes' object has no attribute 'read'
Failed to run APKTool

**Comment by hamakh11** [comment]
same here.

**Comment by SameerShelarr** [comment]
I will suggest using this on Mac OS. Cause it dos not work properly on windows.

**Comment by jayasankarPunnakunnil99** [comment]
I fixed these issues
change  File "C:\Users\samee\AppData\Roaming\Python\Python39\site-packages\qark\decompiler\decompiler.py", line 155, in run_apktool
subprocess.call(shlex.split(custom_apktool_command))
To 
File "C:\Users\samee\AppData\Roaming\Python\Python39\site-packages\qark\decompiler\decompiler.py", line 155, in run_apktool
subprocess.call(shlex.split(custom_apktool_command.decode(encoding="utf-8")))

**Comment by AishwaryaRavindra** [comment]
i am getting the HTML report but it is displaying ERROR in that report.... not displaying the errors also the scan is done very fast 
Decompiling...
Running scans...
Finish scans...
Writing report...
Finish writing report to C:\Users\Hp\AppData\Roaming\Python\Python311\site-packages\qark\report\report.html ...
