### ISSUE TITLE
Error to decompile on Windows using cygwin

### ISSUE THREAD

**Issue by NVolcz** [linkedin/qark#38]
Qark fails to decompile application on Windows using cygwin:
```
Press ENTER key to begin decompilation
Traceback (most recent call last):
  File "qark.py", line 614, in <module>
    unpackAPK.decompile(common.pathToDEX)
  File "/cygdrive/c/Users/admin/gits/qark/modules/unpackAPK.py", line 127, in decompile
    zf = zipfile.ZipFile(common.pathToJar)
  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/cygdrive/c/Users/username/Folder/apkstuffs/app-1.0.0-200-debug/classes_dex2jar.jar'
```

**Comment by tushardalvi** [comment]
Sorry for the inconvenience, but we only support Mac and Linux for now.
