### ISSUE TITLE
Error running dex2jar command

### ISSUE THREAD

**Issue by giridharkl** [linkedin/qark#386]
Platform:
Windows 10
Python 3.8
Java 1.8.0_191
Qark version 4.0.0

Error:
C:\Users\yyyyyyyyyyyyyyy>qark --apk .\Downloads\xxxxxxxxxxyyyyyyyyyyyyyyy.apk
Decompiling...
Error running dex2jar command: b'C:\\\\Users\\\\yyyyyyyyyyyyyy\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\qark\\\\decompiler\\\\..\\\\lib\\\\dex2jar-2.0\\\\d2j-dex2jar.bat C:\\\\Users\\\\yyyyyyyyyyyy\\\\build\\\\qark\\\\classes.dex -o C:\\\\Users\\\\yyyyyyyyy\\\\build\\\\qark\\\\xxxxxxxyyyyyyyyyy.jar'
Traceback (most recent call last):
  File "C:\Users\yyyyyyyyyyyy\AppData\Roaming\Python\Python38\site-packages\qark\decompiler\decompiler.py", line 206, in _run_dex2jar
    ret_code = subprocess.call(shlex.split(dex2jar_command))
  File "c:\python38\lib\shlex.py", line 311, in split
    return list(lex)
  File "c:\python38\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "c:\python38\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "c:\python38\lib\shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'bytes' object has no attribute 'read'
Error running dex2jar command

**Comment by masudr4n4** [comment]
Same here python3.9

**Comment by fengmingye** [comment]
Is problem solved? How?
