### ISSUE TITLE
Manifest parsing bug - UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by 7a** [linkedin/qark#53]
There seems to be a bug in the Manifest parsing code when special characters are encountered:

```
Press ENTER key to continue

INFO - Determined minimum SDK version to be:15

WARNING - Logs are world readable on pre-4.1 devices. A malicious app could potentially retrieve sensitive data from the logs.

ISSUES - APP COMPONENT ATTACK SURFACE

WARNING - Backups enabled: Potential for data theft via local attacks via adb backup, if the device has USB debugging enabled (not common). More info: http://developer.android.com/reference/android/R.attr.html#allowBackup

INFO - Checking provider

INFO - Checking activity

ERROR - Traceback (most recent call last):

  File "qark.py", line 622, in <module>

    act_priv_list=common.normalizeActivityNames(act_priv_list,package_name)

  File "/Users/sevena/qark-master/modules/common.py", line 467, in normalizeActivityNames

    if re.match(r'\..*',str(activityList[d])):

UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeaa' in position 2: ordinal not in range(128)
```

**Comment by tushardalvi** [comment]
We believe this issue is now resolved. Please feel free to retest and let us know if your results vary.
