### ISSUE TITLE
termios error

### ISSUE THREAD

**Issue by AkshayJainG** [linkedin/qark#6]
$ python qark.py
Traceback (most recent call last):
  File "qark.py", line 24, in <module>
    from modules import common,intents,webviews, report, unpackAPK
  File "C:\Users\akshay\Desktop\qark-master\qark-master\modules\common.py", line 26, in <module>
    from lib.blessed import *
  File "C:\Users\akshay\Desktop\qark-master\qark-master\lib\blessed\__init__.py", line 12, in <module>
    from terminal import Terminal
  File "C:\Users\akshay\Desktop\qark-master\qark-master\lib\blessed\terminal.py", line 7, in <module>
    import termios
ImportError: No module named termios

**Comment by tushardalvi** [comment]
Thanks. We are looking into it now. Can you provide us some more details (like the OS you are running this on, whether its a 32/64 bit OS and python version) so we can triage the issue faster.

Cheers,
Tushar

**Comment by AkshayJainG** [comment]
Windows 7 64 bit version and python 2.7

**Comment by SecBro1** [comment]
QARK is not currently designed to support Windows operating systems. We only currently support OSX and Ubuntu Linux (Other versions of Linux may work, but are not supported). We would recommend running one of these in a VM if necessary.
